services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src/chatbot_ui:/app/src/chatbot_ui
    environment:
      - HOME=/app
    command: >
      streamlit run src/chatbot_ui/streamlit_app.py
      --server.address=0.0.0.0
      --server.runOnSave=true
      --server.headless=true
      --server.fileWatcherType=watchdog
      
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped
      

  api:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src/api:/app/src/api